///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class NewsModelResultsMediaMediaMetadata {

  NewsModelResultsMediaMediaMetadata({
    this.url,
    this.format,
    this.height,
    this.width,
  });
  NewsModelResultsMediaMediaMetadata.fromJson(Map<String, dynamic> json) {
    url = json['url']?.toString();
    format = json['format']?.toString();
    height = int.tryParse(json['height']?.toString() ?? '');
    width = int.tryParse(json['width']?.toString() ?? '');
  }
/*
{
  "url": "https://static01.nyt.com/images/2023/07/10/multimedia/10nat-landslide-homes-2-02-wqgf/10nat-landslide-homes-2-02-wqgf-thumbStandard.jpg",
  "format": "Standard Thumbnail",
  "height": 75,
  "width": 75
} 
*/

  String? url;
  String? format;
  int? height;
  int? width;
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['url'] = url;
    data['format'] = format;
    data['height'] = height;
    data['width'] = width;
    return data;
  }
}

class NewsModelResultsMedia {

  NewsModelResultsMedia({
    this.type,
    this.subtype,
    this.caption,
    this.copyright,
    this.approvedForSyndication,
    this.mediaMetadata,
  });
  NewsModelResultsMedia.fromJson(Map<String, dynamic> json) {
    type = json['type']?.toString();
    subtype = json['subtype']?.toString();
    caption = json['caption']?.toString();
    copyright = json['copyright']?.toString();
    approvedForSyndication = int.tryParse(json['approved_for_syndication']?.toString() ?? '');
  if (json['media-metadata'] != null && (json['media-metadata'] is List)) {
  final v = json['media-metadata'];
  final arr0 = <NewsModelResultsMediaMediaMetadata>[];
  v.forEach((v) {
  arr0.add(NewsModelResultsMediaMediaMetadata.fromJson(v  as  Map<String, dynamic>));
  });
    mediaMetadata = arr0;
    }
  }
/*
{
  "type": "image",
  "subtype": "photo",
  "caption": "Utility workers assessed the homes on Monday.",
  "copyright": "Mark Abramson for The New York Times",
  "approved_for_syndication": 1,
  "media-metadata": [
    {
      "url": "https://static01.nyt.com/images/2023/07/10/multimedia/10nat-landslide-homes-2-02-wqgf/10nat-landslide-homes-2-02-wqgf-thumbStandard.jpg",
      "format": "Standard Thumbnail",
      "height": 75,
      "width": 75
    }
  ]
} 
*/

  String? type;
  String? subtype;
  String? caption;
  String? copyright;
  int? approvedForSyndication;
  List<NewsModelResultsMediaMediaMetadata?>? mediaMetadata;
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['type'] = type;
    data['subtype'] = subtype;
    data['caption'] = caption;
    data['copyright'] = copyright;
    data['approved_for_syndication'] = approvedForSyndication;
    if (mediaMetadata != null) {
      final v = mediaMetadata;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['media-metadata'] = arr0;
    }
    return data;
  }
}

class NewsModelResults {

  NewsModelResults({
    this.uri,
    this.url,
    this.id,
    this.assetId,
    this.source,
    this.publishedDate,
    this.updated,
    this.section,
    this.subsection,
    this.nytdsection,
    this.adxKeywords,
    this.column,
    this.byline,
    this.type,
    this.title,
    this.theAbstract,
    this.desFacet,
    this.orgFacet,
    this.perFacet,
    this.geoFacet,
    this.media,
    this.etaId,
  });
  NewsModelResults.fromJson(Map<String, dynamic> json) {
    uri = json['uri']?.toString();
    url = json['url']?.toString();
    id = int.tryParse(json['id']?.toString() ?? '');
    assetId = int.tryParse(json['asset_id']?.toString() ?? '');
    source = json['source']?.toString();
    publishedDate = json['published_date']?.toString();
    updated = json['updated']?.toString();
    section = json['section']?.toString();
    subsection = json['subsection']?.toString();
    nytdsection = json['nytdsection']?.toString();
    adxKeywords = json['adx_keywords']?.toString();
    column = json['column']?.toString();
    byline = json['byline']?.toString();
    type = json['type']?.toString();
    title = json['title']?.toString();
    theAbstract = json['abstract']?.toString();
  if (json['des_facet'] != null && (json['des_facet'] is List)) {
  final v = json['des_facet'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    desFacet = arr0;
    }
  if (json['per_facet'] != null && (json['per_facet'] is List)) {
  final v = json['per_facet'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    perFacet = arr0;
    }
  if (json['geo_facet'] != null && (json['geo_facet'] is List)) {
  final v = json['geo_facet'];
  final arr0 = <String>[];
  v.forEach((v) {
  arr0.add(v.toString());
  });
    geoFacet = arr0;
    }
  if (json['media'] != null && (json['media'] is List)) {
  final v = json['media'];
  final arr0 = <NewsModelResultsMedia>[];
  v.forEach((v) {
  arr0.add(NewsModelResultsMedia.fromJson(v as Map<String, dynamic>));
  });
    media = arr0;
    }
    etaId = int.tryParse(json['eta_id']?.toString() ?? '');
  }
/*
{
  "uri": "nyt://article/79e1713f-1d66-557b-b3db-08fc3925c193",
  "url": "https://www.nytimes.com/2023/07/10/us/california-collapsed-homes-palos-verdes.html",
  "id": 100000008989604,
  "asset_id": 100000008989604,
  "source": "New York Times",
  "published_date": "2023-07-10",
  "updated": "2023-07-11 02:14:49",
  "section": "U.S.",
  "subsection": "",
  "nytdsection": "u.s.",
  "adx_keywords": "Landslides and Mudslides;Hahn, Janice K;California;Los Angeles County (Calif);Palos Verdes (Calif)",
  "column": null,
  "byline": "By Corina Knoll and Shawn Hubler",
  "type": "Article",
  "title": "In Southern California, Hilltop Homes Sink Into a Canyon",
  "abstract": "A landslide destroyed a dozen homes and forced residents to flee a wealthy city on the Palos Verdes Peninsula. The effects of torrential winter storms may be to blame.",
  "des_facet": [
    "Landslides and Mudslides"
  ],
  "org_facet": [
    null
  ],
  "per_facet": [
    "Hahn, Janice K"
  ],
  "geo_facet": [
    "California"
  ],
  "media": [
    {
      "type": "image",
      "subtype": "photo",
      "caption": "Utility workers assessed the homes on Monday.",
      "copyright": "Mark Abramson for The New York Times",
      "approved_for_syndication": 1,
      "media-metadata": [
        {
          "url": "https://static01.nyt.com/images/2023/07/10/multimedia/10nat-landslide-homes-2-02-wqgf/10nat-landslide-homes-2-02-wqgf-thumbStandard.jpg",
          "format": "Standard Thumbnail",
          "height": 75,
          "width": 75
        }
      ]
    }
  ],
  "eta_id": 0
} 
*/

  String? uri;
  String? url;
  int? id;
  int? assetId;
  String? source;
  String? publishedDate;
  String? updated;
  String? section;
  String? subsection;
  String? nytdsection;
  String? adxKeywords;
  String? column;
  String? byline;
  String? type;
  String? title;
  String? theAbstract;
  List<String?>? desFacet;
  List<String?>? orgFacet;
  List<String?>? perFacet;
  List<String?>? geoFacet;
  List<NewsModelResultsMedia?>? media;
  int? etaId;
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['uri'] = uri;
    data['url'] = url;
    data['id'] = id;
    data['asset_id'] = assetId;
    data['source'] = source;
    data['published_date'] = publishedDate;
    data['updated'] = updated;
    data['section'] = section;
    data['subsection'] = subsection;
    data['nytdsection'] = nytdsection;
    data['adx_keywords'] = adxKeywords;
    data['column'] = column;
    data['byline'] = byline;
    data['type'] = type;
    data['title'] = title;
    data['abstract'] = theAbstract;
    if (desFacet != null) {
      final v = desFacet;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['des_facet'] = arr0;
    }
    if (perFacet != null) {
      final v = perFacet;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['per_facet'] = arr0;
    }
    if (geoFacet != null) {
      final v = geoFacet;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v);
  });
      data['geo_facet'] = arr0;
    }
    if (media != null) {
      final v = media;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['media'] = arr0;
    }
    data['eta_id'] = etaId;
    return data;
  }
}

class NewsModel {

  NewsModel({
    this.status,
    this.copyright,
    this.numResults,
    this.results,
  });
  NewsModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    copyright = json['copyright']?.toString();
    numResults = int.tryParse(json['num_results']?.toString() ?? '');
  if (json['results'] != null && (json['results'] is List)) {
  final v = json['results'];
  final arr0 = <NewsModelResults>[];
  v.forEach((v) {
  arr0.add(NewsModelResults.fromJson(v  as Map<String, dynamic>));
  });
    results = arr0;
    }
  }
/*
{
  "status": "OK",
  "copyright": "Copyright (c) 2023 The New York Times Company.  All Rights Reserved.",
  "num_results": 20,
  "results": [
    {
      "uri": "nyt://article/79e1713f-1d66-557b-b3db-08fc3925c193",
      "url": "https://www.nytimes.com/2023/07/10/us/california-collapsed-homes-palos-verdes.html",
      "id": 100000008989604,
      "asset_id": 100000008989604,
      "source": "New York Times",
      "published_date": "2023-07-10",
      "updated": "2023-07-11 02:14:49",
      "section": "U.S.",
      "subsection": "",
      "nytdsection": "u.s.",
      "adx_keywords": "Landslides and Mudslides;Hahn, Janice K;California;Los Angeles County (Calif);Palos Verdes (Calif)",
      "column": null,
      "byline": "By Corina Knoll and Shawn Hubler",
      "type": "Article",
      "title": "In Southern California, Hilltop Homes Sink Into a Canyon",
      "abstract": "A landslide destroyed a dozen homes and forced residents to flee a wealthy city on the Palos Verdes Peninsula. The effects of torrential winter storms may be to blame.",
      "des_facet": [
        "Landslides and Mudslides"
      ],
      "org_facet": [
        null
      ],
      "per_facet": [
        "Hahn, Janice K"
      ],
      "geo_facet": [
        "California"
      ],
      "media": [
        {
          "type": "image",
          "subtype": "photo",
          "caption": "Utility workers assessed the homes on Monday.",
          "copyright": "Mark Abramson for The New York Times",
          "approved_for_syndication": 1,
          "media-metadata": [
            {
              "url": "https://static01.nyt.com/images/2023/07/10/multimedia/10nat-landslide-homes-2-02-wqgf/10nat-landslide-homes-2-02-wqgf-thumbStandard.jpg",
              "format": "Standard Thumbnail",
              "height": 75,
              "width": 75
            }
          ]
        }
      ],
      "eta_id": 0
    }
  ]
} 
*/

  String? status;
  String? copyright;
  int? numResults;
  List<NewsModelResults?>? results;
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['copyright'] = copyright;
    data['num_results'] = numResults;
    if (results != null) {
      final v = results;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data['results'] = arr0;
    }
    return data;
  }
}
